// Copyright (c) The cargo-guppy Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

use crate::{
    helpers::{read_contents, regenerate_lockfile},
    output::{OutputContext, OutputOpts, Styles},
    publish::publish_hakari,
};
use camino::{Utf8Path, Utf8PathBuf};
use clap::Parser;
use color_eyre::eyre::{Result, WrapErr, bail};
use guppy::{
    MetadataCommand, PackageId, Version,
    graph::{PackageGraph, PackageSet},
};
use hakari::{
    DepFormatVersion, Hakari, HakariBuilder, HakariCargoToml, HakariOutputOptions, TomlNameEntry,
    TomlOutError,
    cli_ops::{HakariInit, WorkspaceOps},
    diffy::PatchFormatter,
    summaries::{DEFAULT_CONFIG_PATH, FALLBACK_CONFIG_PATH, HakariConfig},
};
use iddqd::{IdOrdItem, IdOrdMap, id_upcast};
use log::{error, info};
use owo_colors::OwoColorize;
use std::{collections::BTreeMap, convert::TryFrom, fmt};

/// The comment to add to the top of the config file.
pub static CONFIG_COMMENT: &str = r#"# This file contains settings for `cargo hakari`.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/config for a full list of options.
"#;

/// The comment to add to the top of the workspace-hack package's Cargo.toml.
pub static CARGO_TOML_COMMENT: &str = r#"# This file is generated by `cargo hakari`.
# To regenerate, run:
#     cargo hakari generate
"#;

/// The message to write into a disabled Cargo.toml.
pub static DISABLE_MESSAGE: &str = r#"
# Disabled by running `cargo hakari disable`.
# To re-enable, run:
#     cargo hakari generate
"#;

/// Set up and manage workspace-hack crates.
///
/// For more about cargo-hakari, see <https://docs.rs/cargo-hakari>.
#[derive(Debug, Parser)]
#[clap(author, version, about)]
pub struct Args {
    #[clap(flatten)]
    global: GlobalOpts,
    #[clap(subcommand)]
    command: Command,
}

impl Args {
    /// Executes the command.
    ///
    /// Returns the exit status, or an error on failure.
    pub fn exec(self) -> Result<i32> {
        self.command.exec(self.global.output)
    }
}

#[derive(Debug, Parser)]
struct GlobalOpts {
    #[clap(flatten)]
    output: OutputOpts,
}

/// Manage workspace-hack crates.
#[derive(Debug, Parser)]
enum Command {
    /// Initialize a workspace-hack crate and a hakari.toml file
    #[clap(name = "init")]
    Initialize {
        /// Path to generate the workspace-hack crate at, relative to the current directory.
        path: Utf8PathBuf,

        /// The name of the crate (default: derived from path)
        #[clap(long, short)]
        package_name: Option<String>,

        /// Skip writing a stub config to hakari.toml
        #[clap(long)]
        skip_config: bool,

        /// Print operations that need to be performed, but do not actually perform them.
        ///
        /// Exits with status 1 if any operations need to be performed. Can be combined with
        /// `--quiet`.
        #[clap(long, short = 'n', conflicts_with = "yes")]
        dry_run: bool,

        /// Proceed with the operation without prompting for confirmation.
        #[clap(long, short, conflicts_with = "dry_run")]
        yes: bool,
    },

    #[clap(flatten)]
    WithBuilder(CommandWithBuilder),
}

impl Command {
    fn exec(self, output: OutputOpts) -> Result<i32> {
        let output = output.init();
        let metadata_command = MetadataCommand::new();
        let package_graph = metadata_command
            .build_graph()
            .context("building package graph failed")?;

        match self {
            Command::Initialize {
                path,
                package_name,
                skip_config,
                dry_run,
                yes,
            } => {
                let package_name = match package_name.as_deref() {
                    Some(name) => name,
                    None => match path.file_name() {
                        Some(name) => name,
                        None => bail!("invalid path {}", path),
                    },
                };

                let workspace_path =
                    cwd_rel_to_workspace_rel(&path, package_graph.workspace().root())?;

                let mut init = HakariInit::new(&package_graph, package_name, &workspace_path)
                    .with_context(|| "error initializing Hakari package")?;
                init.set_cargo_toml_comment(CARGO_TOML_COMMENT);
                if !skip_config {
                    init.set_config(DEFAULT_CONFIG_PATH.as_ref(), CONFIG_COMMENT)
                        .with_context(|| "error initializing Hakari package")?;
                }

                let ops = init.make_ops();
                apply_on_dialog(dry_run, yes, &ops, &output, || {
                    let steps = [
                        format!(
                            "* configure at {}",
                            DEFAULT_CONFIG_PATH.style(output.styles.config_path),
                        ),
                        format!(
                            "* run {} to generate contents",
                            "cargo hakari generate".style(output.styles.command),
                        ),
                        format!(
                            "* run {} to add dependency lines",
                            "cargo hakari manage-deps".style(output.styles.command),
                        ),
                    ];
                    info!("next steps:\n{}\n", steps.join("\n"));
                    Ok(())
                })
            }
            Command::WithBuilder(cmd) => {
                let (builder, hakari_output) = make_builder_and_output(&package_graph)?;
                cmd.exec(builder, hakari_output, output)
            }
        }
    }
}

#[derive(Debug, Parser)]
enum CommandWithBuilder {
    /// Generate or update the contents of the workspace-hack crate
    Generate {
        /// Print a diff of contents instead of writing them out. Can be combined with `--quiet`.
        ///
        /// Exits with status 1 if the contents are different.
        #[clap(long)]
        diff: bool,
    },

    /// Perform verification of the workspace-hack crate
    ///
    /// Check that the workspace-hack crate succeeds at its goal of building one version of
    /// every non-omitted third-party crate.
    ///
    /// Exits with status 1 if verification failed.
    Verify,

    /// Manage dependencies from workspace crates to workspace-hack.
    ///
    /// * Add the dependency to all non-excluded workspace crates.
    /// * Remove the dependency from all excluded workspace crates.
    ///
    /// A workspace crate is *managed* if it isn't the workspace-hack itself and
    /// isn't listed in `traversal-excludes` or `final-excludes`. For each
    /// selected crate, what happens depends on its existing dependency on the
    /// workspace-hack, if any:
    ///
    /// ```text
    /// Crate     Existing dependency on workspace-hack    Action
    /// --------  ---------------------------------------  ---------------------------
    /// managed   none                                     add to [dependencies]
    /// managed   only [dev-dependencies] and/or           add to [dependencies], and
    ///           [build-dependencies] (top-level or       remove the [dev-dependencies]
    ///           under [target.*])                        line
    /// managed   unconditional [dependencies]             keep; update the line if
    ///                                                    needed (see below)
    /// managed   only under [target.*], or optional       keep as is
    /// excluded  any                                      remove from every section,
    ///                                                    including [target.*]
    /// excluded  none                                     nothing
    /// ```
    ///
    /// A line needs updating if its version requirement doesn't match the
    /// workspace-hack's version, or if it has no version requirement and
    /// `workspace-hack-line-style` isn't `"workspace-dotted"`.
    ///
    /// Platform-specific lines under `[target.*]` and optional lines count as
    /// present and are never rewritten, so crates that deliberately gate the
    /// workspace-hack (for example, to keep it out of builds on certain
    /// platforms) are left alone. A `[build-dependencies]` line is retained
    /// when adding dependency lines, since it pulls the workspace-hack into the
    /// host build on purpose.
    ManageDeps {
        #[clap(flatten)]
        packages: PackageSelection,

        /// Print operations that need to be performed, but do not actually perform them.
        ///
        /// Exits with status 1 if any operations need to be performed. Can be combined with
        /// `--quiet`.
        #[clap(long, short = 'n', conflicts_with = "yes")]
        dry_run: bool,

        /// Proceed with the operation without prompting for confirmation.
        #[clap(long, short, conflicts_with = "dry_run")]
        yes: bool,
    },

    /// Remove dependencies from workspace crates to workspace-hack.
    ///
    /// The dependency is removed from every section it appears in, including
    /// `[dev-dependencies]`, `[build-dependencies]` and the sections under
    /// `[target.*]`.
    RemoveDeps {
        #[clap(flatten)]
        packages: PackageSelection,

        /// Print operations that need to be performed, but do not actually perform them.
        ///
        /// Exits with status 1 if any operations need to be performed. Can be combined with
        /// `--quiet`.
        #[clap(long, short = 'n', conflicts_with = "yes")]
        dry_run: bool,

        /// Proceed with the operation without prompting for confirmation.
        #[clap(long, short, conflicts_with = "dry_run")]
        yes: bool,
    },

    /// Print out workspace crates responsible for adding a dependency to workspace-hack.
    ///
    /// For a dependency to be included in the workspace-hack, it must have been built with at least
    /// two different feature sets by different crates in the workspace (unless the
    /// output-single-feature option is set to true). The explain command prints out a table
    /// consisting of the different feature sets that got built; and, for each feature set, the
    /// workspace crates and options that resulted in it.
    ///
    /// Adding the initial set of dependencies to the workspace-hack can cause further dependencies
    /// to be added if they're built with a second feature set. These cases are marked as
    /// "post-compute fixup".
    ///
    /// Currently, this command only prints out the different feature sets that get built for a
    /// dependency, and the workspace crates responsible for them. Further investigation can be done
    /// through `cargo tree`. In the future, the scope of this command may be extended to provide
    /// information about intermediate dependencies as well.
    Explain {
        /// The name of the dependency, as present in the workspace-hack.
        dep_name: String,
    },

    /// Publish a package after temporarily removing the workspace-hack dependency from it.
    ///
    /// For more information about publishing options,
    /// see {n}https://docs.rs/cargo-hakari/latest/cargo_hakari/publishing.
    ///
    /// Trailing arguments are passed through to cargo publish.
    #[clap(trailing_var_arg = true, allow_hyphen_values = true)]
    Publish {
        /// The name of the package to publish.
        #[clap(long, short)]
        package: String,

        /// Arguments to pass through to `cargo publish`.
        #[clap(num_args = 0..)]
        pass_through: Vec<String>,
    },

    /// Disables the workspace-hack crate.
    ///
    /// Removes all the generated contents from the workspace-hack crate.
    Disable {
        /// Print a diff of changes instead of writing them out. Can be combined with `--quiet`.
        ///
        /// Exits with status 1 if the contents are different.
        #[clap(long)]
        diff: bool,
    },
}

impl CommandWithBuilder {
    fn exec(
        self,
        builder: HakariBuilder<'_>,
        hakari_output: HakariOutputOptions,
        output: OutputContext,
    ) -> Result<i32> {
        let hakari_package = *builder
            .hakari_package()
            .expect("hakari-package must be specified in hakari.toml");

        match self {
            CommandWithBuilder::Generate { diff } => {
                let package_graph = builder.graph();
                let hakari = builder.compute();
                let toml_out = match hakari.to_toml_string(&hakari_output) {
                    Ok(toml_out) => toml_out,
                    Err(TomlOutError::UnrecognizedRegistry {
                        package_id,
                        registry_url,
                    }) => {
                        // Print out a better error message for this more common use case.
                        let package = package_graph
                            .metadata(&package_id)
                            .expect("package ID obtained from the same graph");
                        error!(
                            "unrecognized registry URL {} found for {} v{}\n\
                             (add to [registries] section of {})",
                            registry_url.style(output.styles.registry_url),
                            package.name().style(output.styles.package_name),
                            package.version().style(output.styles.package_version),
                            "hakari.toml".style(output.styles.config_path),
                        );
                        // 102 is picked pretty arbitrarily because regular errors exit with 101.
                        return Ok(102);
                    }
                    Err(
                        err @ TomlOutError::Platform(_)
                        | err @ TomlOutError::Toml { .. }
                        | err @ TomlOutError::FmtWrite(_)
                        | err @ TomlOutError::UnrecognizedExternal { .. }
                        | err @ TomlOutError::PathWithoutHakari { .. }
                        | err,
                    ) => Err(err).with_context(|| "error generating new hakari.toml")?,
                };

                let existing_toml = hakari
                    .read_toml()
                    .expect("hakari-package must be specified")?;

                let exit_code =
                    write_to_cargo_toml(existing_toml, &toml_out, diff, output.clone())?;
                if hakari.builder().dep_format_version() < DepFormatVersion::latest() {
                    info!(
                        "new hakari format version available: {latest} (current: {})\n\
                        (add or update `dep-format-version = \"{latest}\"` in {}, then run \
                        `cargo hakari generate && cargo hakari manage-deps`)",
                        hakari.builder().dep_format_version(),
                        "hakari.toml".style(output.styles.config_path),
                        latest = DepFormatVersion::latest(),
                    );
                }

                Ok(exit_code)
            }
            CommandWithBuilder::Verify => match builder.verify() {
                Ok(()) => {
                    info!(
                        "{} works correctly",
                        hakari_package.name().style(output.styles.package_name),
                    );
                    Ok(0)
                }
                Err(errs) => {
                    let mut display = errs.display();
                    if output.color.is_enabled() {
                        display.colorize();
                    }
                    info!(
                        "{} didn't work correctly:\n{}",
                        hakari_package.name().style(output.styles.package_name),
                        display,
                    );
                    Ok(1)
                }
            },
            CommandWithBuilder::ManageDeps {
                packages,
                dry_run,
                yes,
            } => {
                let ops = builder
                    .manage_dep_ops(&packages.to_package_set(builder.graph())?)
                    .expect("hakari-package must be specified in hakari.toml");
                if ops.is_empty() {
                    info!("no operations to perform");
                    return Ok(0);
                }

                apply_on_dialog(dry_run, yes, &ops, &output, || {
                    regenerate_lockfile(output.clone())
                })
            }
            CommandWithBuilder::RemoveDeps {
                packages,
                dry_run,
                yes,
            } => {
                let ops = builder
                    .remove_dep_ops(&packages.to_package_set(builder.graph())?, false)
                    .expect("hakari-package must be specified in hakari.toml");
                if ops.is_empty() {
                    info!("no operations to perform");
                    return Ok(0);
                }

                apply_on_dialog(dry_run, yes, &ops, &output, || {
                    regenerate_lockfile(output.clone())
                })
            }
            CommandWithBuilder::Explain {
                dep_name: crate_name,
            } => {
                let hakari = builder.compute();
                let toml_name_map = hakari.toml_name_map();
                let dep = match CrateLookup::lookup(&hakari, &toml_name_map, &crate_name)? {
                    CrateLookup::Found(entry) => entry,
                    CrateLookup::NotFound(reason) => {
                        error!(
                            "{}",
                            reason.display(hakari_package.name(), &crate_name, &output.styles)
                        );
                        return Ok(1);
                    }
                };

                let explain = hakari
                    .explain(dep.package().id())
                    .expect("package ID should be known since it was in the output");
                let mut display = explain.display();
                if output.color.is_enabled() {
                    display.colorize();
                }
                info!("\n{display}");
                Ok(0)
            }
            CommandWithBuilder::Publish {
                package,
                pass_through,
            } => {
                publish_hakari(&package, builder, &pass_through, output)?;
                Ok(0)
            }
            CommandWithBuilder::Disable { diff } => {
                let existing_toml = builder
                    .read_toml()
                    .expect("hakari-package must be specified")?;
                write_to_cargo_toml(existing_toml, DISABLE_MESSAGE, diff, output)
            }
        }
    }
}

/// Support for packages and features.
#[derive(Debug, Parser)]
struct PackageSelection {
    #[clap(long = "package", short)]
    /// Packages to operate on (default: entire workspace)
    packages: Vec<String>,
}

impl PackageSelection {
    /// Converts this selection into a `PackageSet`.
    fn to_package_set<'g>(&self, graph: &'g PackageGraph) -> Result<PackageSet<'g>> {
        if !self.packages.is_empty() {
            Ok(graph.resolve_workspace_names(&self.packages)?)
        } else {
            Ok(graph.resolve_workspace())
        }
    }
}

// ---
// Helper methods
// ---

/// The result of looking up a crate name in the workspace-hack.
#[derive(Debug)]
enum CrateLookup<'g, 'a> {
    /// The crate is written out under this entry.
    Found(&'a TomlNameEntry<'g>),
    /// The crate is not in the workspace-hack, and this is why.
    NotFound(NotFoundReason),
}

impl<'g, 'a> CrateLookup<'g, 'a> {
    fn lookup(
        hakari: &Hakari<'g>,
        toml_name_map: &'a IdOrdMap<TomlNameEntry<'g>>,
        crate_name: &str,
    ) -> Result<Self, guppy::Error> {
        if let Some(entry) = toml_name_map.get(crate_name) {
            return Ok(Self::Found(entry));
        }

        let hashed_names: BTreeMap<String, Version> = toml_name_map
            .iter()
            .filter(|entry| entry.package().name() == crate_name)
            .map(|entry| {
                (
                    entry.toml_name().as_str().to_owned(),
                    entry.package().version().clone(),
                )
            })
            .collect();
        if !hashed_names.is_empty() {
            return Ok(Self::NotFound(NotFoundReason::MultipleVersions {
                hashed_names,
            }));
        }

        let builder = hakari.builder();
        let mut packages = IdOrdMap::new();
        for package in builder.graph().packages() {
            // Workspace members, including the hakari package, can never be
            // added regardless of configuration, so they're reported via
            // member_by_name below rather than as excluded.
            if package.name() != crate_name || package.in_workspace() {
                continue;
            }
            let traversal = builder.is_traversal_excluded(package.id())?;
            let final_ = builder.is_final_excluded(package.id())?;
            let Some(by) = ExcludedBy::from_flags(traversal, final_) else {
                continue;
            };
            packages
                .insert_unique(ExcludedPackage {
                    id: package.id().clone(),
                    version: package.version().clone(),
                    by,
                })
                .expect("package IDs within a graph are unique");
        }
        if !packages.is_empty() {
            return Ok(Self::NotFound(NotFoundReason::ConfigExcluded { packages }));
        }

        // member_by_name only fails with UnknownWorkspaceName, but it returns
        // the general error type.
        #[cfg_attr(guppy_nightly, expect(non_exhaustive_omitted_patterns))]
        match builder.graph().workspace().member_by_name(crate_name) {
            Ok(package) => Ok(Self::NotFound(NotFoundReason::WorkspaceMember {
                id: package.id().clone(),
                version: package.version().clone(),
            })),
            Err(guppy::Error::UnknownWorkspaceName(_)) => {
                Ok(Self::NotFound(NotFoundReason::Unknown))
            }
            Err(error) => Err(error),
        }
    }
}

/// The reason a crate name wasn't found in the workspace hack.
#[derive(Debug, PartialEq, Eq)]
enum NotFoundReason {
    /// The crate has more than one version in the workspace hack.
    MultipleVersions {
        /// The hashed names and versions of crates.
        hashed_names: BTreeMap<String, Version>,
    },
    /// The crate is excluded by the configuration.
    ConfigExcluded {
        /// All packages with this name excluded by the configuration.
        packages: IdOrdMap<ExcludedPackage>,
    },
    /// The crate is a workspace member and so is ineligible to be included in
    /// the workspace hack.
    WorkspaceMember { id: PackageId, version: Version },
    /// This crate name is unknown.
    Unknown,
}

#[derive(Debug, PartialEq, Eq)]
struct ExcludedPackage {
    id: PackageId,
    version: Version,
    by: ExcludedBy,
}

impl IdOrdItem for ExcludedPackage {
    type Key<'a> = &'a PackageId;

    fn key(&self) -> Self::Key<'_> {
        &self.id
    }

    id_upcast!();
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum ExcludedBy {
    TraversalExcludes,
    FinalExcludes,
    Both,
}

impl NotFoundReason {
    fn display<'a>(
        &'a self,
        hakari_name: &'a str,
        crate_name: &'a str,
        styles: &'a Styles,
    ) -> NotFoundReasonDisplay<'a> {
        NotFoundReasonDisplay {
            reason: self,
            hakari_name,
            crate_name,
            styles,
        }
    }
}

/// A display formatter for [`NotFoundReason`].
#[derive(Clone, Copy, Debug)]
struct NotFoundReasonDisplay<'a> {
    reason: &'a NotFoundReason,
    hakari_name: &'a str,
    crate_name: &'a str,
    styles: &'a Styles,
}

impl fmt::Display for NotFoundReasonDisplay<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let crate_name = self.crate_name.style(self.styles.package_name);
        let hakari_name = self.hakari_name.style(self.styles.package_name);
        match self.reason {
            NotFoundReason::MultipleVersions { hashed_names } => {
                write!(
                    f,
                    "crate '{crate_name}' has multiple versions in {hakari_name}; \
                     specify one of: "
                )?;
                for (i, (toml_name, version)) in hashed_names.iter().enumerate() {
                    if i > 0 {
                        f.write_str(", ")?;
                    }
                    write!(
                        f,
                        "{toml_name} (v{})",
                        version.style(self.styles.package_version)
                    )?;
                }
                Ok(())
            }
            NotFoundReason::ConfigExcluded { packages } => {
                write!(
                    f,
                    "crate '{crate_name}' is excluded by `hakari.toml`, \
                     so it is never added to {hakari_name}: "
                )?;
                for (i, package) in packages.iter().enumerate() {
                    if i > 0 {
                        f.write_str(", ")?;
                    }
                    write!(
                        f,
                        "v{} ({})",
                        package.version.style(self.styles.package_version),
                        package.by.config_keys(),
                    )?;
                }
                Ok(())
            }
            NotFoundReason::WorkspaceMember { id: _, version } => {
                write!(
                    f,
                    "crate '{crate_name}' v{} is a workspace member; hakari only adds \
                     third-party dependencies to {hakari_name}",
                    version.style(self.styles.package_version),
                )
            }
            NotFoundReason::Unknown => {
                write!(
                    f,
                    "crate name '{crate_name}' not found in workspace-hack\n\
                     (hint: check spelling, or regenerate workspace-hack with \
                     `cargo hakari generate`)"
                )
            }
        }
    }
}

impl ExcludedBy {
    fn from_flags(traversal: bool, final_: bool) -> Option<Self> {
        match (traversal, final_) {
            (true, true) => Some(Self::Both),
            (true, false) => Some(Self::TraversalExcludes),
            (false, true) => Some(Self::FinalExcludes),
            (false, false) => None,
        }
    }

    fn config_keys(&self) -> &'static str {
        match self {
            Self::TraversalExcludes => "traversal-excludes",
            Self::FinalExcludes => "final-excludes",
            Self::Both => "traversal-excludes and final-excludes",
        }
    }
}

fn cwd_rel_to_workspace_rel(path: &Utf8Path, workspace_root: &Utf8Path) -> Result<Utf8PathBuf> {
    let abs_path = if path.is_absolute() {
        path.to_owned()
    } else {
        let cwd = std::env::current_dir().with_context(|| "could not access current dir")?;
        let mut cwd = Utf8PathBuf::try_from(cwd).with_context(|| "current dir is invalid UTF-8")?;
        cwd.push(path);
        cwd
    };

    abs_path
        .strip_prefix(workspace_root)
        .map(|p| p.to_owned())
        .with_context(|| format!("path {abs_path} is not inside workspace root {workspace_root}"))
}

fn make_builder_and_output(
    package_graph: &PackageGraph,
) -> Result<(HakariBuilder<'_>, HakariOutputOptions)> {
    let (config_path, contents) = read_contents(
        package_graph.workspace().root(),
        [DEFAULT_CONFIG_PATH, FALLBACK_CONFIG_PATH],
    )
    .wrap_err("error reading Hakari config")?;

    let config: HakariConfig = contents
        .parse()
        .wrap_err_with(|| format!("error deserializing Hakari config at {config_path}"))?;

    let builder = config
        .builder
        .to_hakari_builder(package_graph)
        .wrap_err_with(|| format!("error resolving Hakari config at {config_path}"))?;
    let hakari_output = config.output.to_options();

    Ok((builder, hakari_output))
}

fn write_to_cargo_toml(
    existing_toml: HakariCargoToml,
    new_contents: &str,
    diff: bool,
    output: OutputContext,
) -> Result<i32> {
    if diff {
        let patch = existing_toml.diff_toml(new_contents);
        if patch.hunks().is_empty() {
            // No differences.
            Ok(0)
        } else {
            let mut formatter = PatchFormatter::new();
            if output.color.is_enabled() {
                formatter = formatter.with_color();
            }
            info!("\n{}", formatter.fmt_patch(&patch));
            Ok(1)
        }
    } else {
        if !existing_toml.is_changed(new_contents) {
            info!("no changes detected");
        } else {
            existing_toml
                .write_to_file(new_contents)
                .with_context(|| "error writing updated Hakari contents")?;
            info!("contents updated");
            regenerate_lockfile(output)?;
        }
        Ok(0)
    }
}

fn apply_on_dialog(
    dry_run: bool,
    yes: bool,
    ops: &WorkspaceOps<'_, '_>,
    output: &OutputContext,
    after: impl FnOnce() -> Result<()>,
) -> Result<i32> {
    let mut display = ops.display();
    if output.color.is_enabled() {
        display.colorize();
    }
    info!("operations to perform:\n\n{display}");

    if dry_run {
        // dry-run + non-empty ops implies exit status 1.
        return Ok(1);
    }

    let should_apply = if yes {
        true
    } else {
        let colorful_theme = dialoguer::theme::ColorfulTheme::default();
        let confirm = if output.color.is_enabled() {
            dialoguer::Confirm::with_theme(&colorful_theme)
        } else {
            dialoguer::Confirm::with_theme(&dialoguer::theme::SimpleTheme)
        };
        confirm
            .with_prompt("proceed?")
            .default(true)
            .show_default(true)
            .interact()
            .with_context(|| "error reading input")?
    };

    if should_apply {
        ops.apply()?;
        after()?;
        Ok(0)
    } else {
        Ok(1)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use fixtures::json::{
        JsonFixture, METADATA_HAKARI_REVERSE_DEP_LEAF, METADATA_HAKARI_REVERSE_DEP_MEMBER_FEATURES,
        METADATA_HAKARI_REVERSE_DEP_MEMBER_NORMAL, METADATA_HAKARI_REVERSE_DEP_WORKSPACE_HACK,
    };

    /// Configuration excludes to apply to the hakari-reverse-dep fixture, as
    /// package IDs.
    #[derive(Default)]
    struct Excludes {
        traversal: Vec<&'static str>,
        final_: Vec<&'static str>,
    }

    fn reverse_dep_hakari(excludes: Excludes) -> Hakari<'static> {
        let fixture = JsonFixture::metadata_hakari_reverse_dep();
        let graph = fixture.graph();
        let hakari_id = fixture
            .details()
            .hakari_package()
            .expect("hakari-reverse-dep fixture names a hakari package");
        let mut builder =
            HakariBuilder::new(graph, Some(hakari_id)).expect("hakari builder is created");
        let traversal: Vec<PackageId> = excludes
            .traversal
            .iter()
            .map(|id| PackageId::new(*id))
            .collect();
        builder
            .add_traversal_excludes(&traversal)
            .expect("traversal excludes are known to the graph");
        let final_: Vec<PackageId> = excludes
            .final_
            .iter()
            .map(|id| PackageId::new(*id))
            .collect();
        builder
            .add_final_excludes(&final_)
            .expect("final excludes are known to the graph");
        builder.compute()
    }

    fn not_found_reason(hakari: &Hakari<'_>, crate_name: &str) -> NotFoundReason {
        let toml_name_map = hakari.toml_name_map();
        match CrateLookup::lookup(hakari, &toml_name_map, crate_name)
            .expect("lookup completes without a graph error")
        {
            CrateLookup::Found(entry) => panic!(
                "crate '{crate_name}' is unexpectedly in the workspace-hack as '{}'",
                entry.toml_name()
            ),
            CrateLookup::NotFound(reason) => reason,
        }
    }

    #[test]
    fn explain_found() {
        let hakari = reverse_dep_hakari(Excludes::default());
        let toml_name_map = hakari.toml_name_map();
        match CrateLookup::lookup(&hakari, &toml_name_map, "hrd-leaf")
            .expect("lookup completes without a graph error")
        {
            CrateLookup::Found(entry) => {
                assert_eq!(entry.toml_name().as_str(), "hrd-leaf");
                assert_eq!(
                    entry.package().id(),
                    &PackageId::new(METADATA_HAKARI_REVERSE_DEP_LEAF)
                );
            }
            CrateLookup::NotFound(reason) => {
                panic!("hrd-leaf should be in the workspace-hack, but got {reason:?}")
            }
        }
    }

    #[test]
    fn explain_not_found_workspace_member() {
        let hakari = reverse_dep_hakari(Excludes::default());
        assert_eq!(
            not_found_reason(&hakari, "hrd-member-features"),
            NotFoundReason::WorkspaceMember {
                id: PackageId::new(METADATA_HAKARI_REVERSE_DEP_MEMBER_FEATURES),
                version: Version::new(0, 1, 0),
            },
        );
    }

    #[test]
    fn explain_not_found_hakari_package() {
        // The hakari algorithm treats the hakari package as traversal-excluded
        // -- it must not be reported as a config exclude.
        let hakari = reverse_dep_hakari(Excludes::default());
        assert_eq!(
            not_found_reason(&hakari, "hrd-workspace-hack"),
            NotFoundReason::WorkspaceMember {
                id: PackageId::new(METADATA_HAKARI_REVERSE_DEP_WORKSPACE_HACK),
                version: Version::new(0, 1, 0),
            },
        );
    }

    #[test]
    fn explain_not_found_workspace_member_in_traversal_excludes() {
        let hakari = reverse_dep_hakari(Excludes {
            traversal: vec![METADATA_HAKARI_REVERSE_DEP_MEMBER_NORMAL],
            ..Excludes::default()
        });
        assert_eq!(
            not_found_reason(&hakari, "hrd-member-normal"),
            NotFoundReason::WorkspaceMember {
                id: PackageId::new(METADATA_HAKARI_REVERSE_DEP_MEMBER_NORMAL),
                version: Version::new(0, 1, 0),
            },
        );
    }

    #[test]
    fn explain_not_found_config_excluded() {
        let leaf = vec![METADATA_HAKARI_REVERSE_DEP_LEAF];
        let cases = [
            (
                Excludes {
                    traversal: leaf.clone(),
                    final_: vec![],
                },
                ExcludedBy::TraversalExcludes,
            ),
            (
                Excludes {
                    traversal: vec![],
                    final_: leaf.clone(),
                },
                ExcludedBy::FinalExcludes,
            ),
            (
                Excludes {
                    traversal: leaf.clone(),
                    final_: leaf,
                },
                ExcludedBy::Both,
            ),
        ];
        for (excludes, by) in cases {
            let hakari = reverse_dep_hakari(excludes);
            assert_eq!(
                not_found_reason(&hakari, "hrd-leaf"),
                NotFoundReason::ConfigExcluded {
                    packages: IdOrdMap::from_iter_unique([ExcludedPackage {
                        id: PackageId::new(METADATA_HAKARI_REVERSE_DEP_LEAF),
                        version: Version::new(0, 1, 0),
                        by,
                    }])
                    .expect("expected excluded packages have unique IDs"),
                },
                "hrd-leaf excluded by {by:?}",
            );
        }
    }

    #[test]
    fn explain_not_found_multiple_versions() {
        let graph = JsonFixture::metadata_libra().graph();
        let hakari = HakariBuilder::new(graph, None)
            .expect("hakari builder is created")
            .compute();
        assert_eq!(
            not_found_reason(&hakari, "rand_core"),
            NotFoundReason::MultipleVersions {
                hashed_names: BTreeMap::from([
                    (
                        "rand_core-468e82937335b1c9".to_owned(),
                        Version::new(0, 3, 1),
                    ),
                    (
                        "rand_core-9fbad63c4bcf4a8f".to_owned(),
                        Version::new(0, 4, 2),
                    ),
                ]),
            },
        );
    }

    #[test]
    fn explain_not_found_unknown() {
        let hakari = reverse_dep_hakari(Excludes::default());
        assert_eq!(
            not_found_reason(&hakari, "hrd-not-a-real-crate"),
            NotFoundReason::Unknown,
        );
    }
}
