# This workflow file serves as an example for cargo-hakari CI integration.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: cargo hakari

concurrency:
  # Cancel in-progress runs when a PR branch is updated.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  workspace-hack-check:
    name: Check workspace-hack
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@686976e191b89faba57d3206551f0f330d8cb249 # stable
      - name: Install cargo-hakari
        uses: taiki-e/install-action@f7e5d7c961414b23f5b25b2da9294395d08513ad # v2
        with:
          tool: cargo-hakari
      - name: Check workspace-hack Cargo.toml is up-to-date
        run: cargo hakari generate --diff
      - name: Check all crates depend on workspace-hack
        run: cargo hakari manage-deps --dry-run
